#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

VERSION="2.1.20"
URL="https://github.com/nilsteampassnet/TeamPass/archive/${VERSION}.zip"

dl $URL /usr/local/src

